[tool.pyrefly]
venvPath = "."
venv = ".venv"
project-excludes = [
    "**/_pyrefly_virtual_/**",
    "**/inmemory/**",
    "**/agents/**",
    "**/.antigravity/**",
    "**/agent_chat/**"
]
project-includes = [
    "posture_app/**/*.py"
]